### PR TITLE
Loklak modular

### PR DESCRIPTION
**Pull request by abdulhannanali**

### CODE REVIEW

**Comment by abdulhannanali** [comment]
@sudheesh001 this pull request implements the 2 step way

**Comment by sudheesh001** [comment]
@abdulhannanali Could you add the screenshots to the readme file ?

**Comment by abdulhannanali** [comment]
@sudheesh001 after closing the two issues yes! they just are related to the ux

**Comment by abdulhannanali** [comment]
here's the one for you though...

**Comment by abdulhannanali** [comment]
@sudheesh001 done! screenshots added to the [README.md](README.md). UX issues have to be solved still though

**Pull request merged**
